site_name: Jianjun Zhou's Notebook
site_url: https://ZhouTimeMachine.github.io/note
repo_name: ZhouTimeMachine/note
repo_url: https://github.com/ZhouTimeMachine/note/
edit_uri: tree/master/docs
site_description: Jianjun Zhou's Notebook
copyright: Copyright &copy; 2023 <a href="https://github.com/ZhouTimeMachine" target="_blank" rel="noopener">ZhouTimeMachine</a>

nav:
  - Home:
    - index.md
  - Courses:
    - courses/index.md
    - Theory of Computation: courses/toc-review.md
    - Advanced Data Structure and Algorithm:
      - Homework: courses/ads-hw-review.md
      - Final Review: courses/ads-final-review.md
    - Object Oriented Programming:
      - Midterm Review: courses/oop-mid-review.md
      - Final Review: courses/oop-final-review.md
    - Database System: 
      - Chapter 1-7: courses/db-ch1-to-7-review.md
      - Chapter 12-19: courses/db-ch12-to-19-review.md
    - Probability Theory: courses/probability-review.md
    - Physics (H):
      - Physics 1: courses/physics1-review.md
      - Physics 2: courses/physics2-review.md
    - C Programming: courses/C-review.md

theme: 
  name: 'material'
  language: 'en'
  icon: 
    logo: material/notebook-outline
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 夜间模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 日间模式
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false

markdown_extensions:
  - admonition # mkdocs warning
  - md_in_html # footnote
  - meta # metadata
  - pymdownx.caret # underline
  - pymdownx.mark # text hightlight
  - pymdownx.tilde # strikethrough
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.arithmatex: # TeX support for math formula
      generic: true
  - pymdownx.emoji: # emoji support
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.tasklist: # tasklist support
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables
#   - toc:
#       permalink: true
#       toc_depth: 4
#   - def_list
#   - attr_list
#   - sane_lists

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://fonts.googleapis.com/css?family=Roboto:500,500i,600,600i&display=fallback
  - css/custom.css

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js
  - js/heti.js

plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: en
      enable_creation_date: true
      exclude:
        - index.md